#!/usr/bin/env python
import csv
import pprint
import subprocess
import sys
import argparse

interval = 30
SMCLI = "/opt/dell/mdstoragemanager/client/SMcli"

def write_metric(plugin_instance,type_instance,value, host):
    print "PUTVAL %s/disk-%s/%s interval=%s N:%s" % (host,plugin_instance,type_instance,interval,value)

def write_metrics( metrics, host):
    for ld in metrics:
        for key,value in metrics[ld].iteritems():
            write_metric(ld, key, value, host)

def get_metrics(host,controllera,controllerb):
        metrics = {}

        #controller A
        cmd_a = subprocess.Popen([SMCLI, controllera, "-S", "-quick",
                                "-c", "set session performanceMonitorInterval=%s; show allVirtualDisks performanceStats;"%interval], 
                                 stdout=subprocess.PIPE)
        reader_a = csv.reader(cmd_a.stdout, delimiter=',', quotechar='"')

        #controller B
        cmd_b = subprocess.Popen([SMCLI, controllerb, "-S", "-quick",
                                "-c", "set session performanceMonitorInterval=%s; show allVirtualDisks performanceStats;"%interval], 
                                 stdout=subprocess.PIPE)
        reader_b = csv.reader(cmd_b.stdout, delimiter=',', quotechar='"')
        
        #controller A
        cmd_a.wait()
        for r in range(0,7):
            reader_a.next()
        for line in reader_a:
            lineiter = iter(line)
            ld = lineiter.next().replace("Virtual Disk ","")
	    metrics[ld] = {}
            lineiter.next() # Ignore Total IOs

            metrics[ld]["percent-read_ratio"] = float(lineiter.next())
            metrics[ld]["percent-primary_read_cache_hit"] = float(lineiter.next())
            metrics[ld]["percent-primary_write_cache_hit"] = float(lineiter.next())
            lineiter.next() # Ignore SSD read cache hit
            metrics[ld]["gauge-throughput"] = float(lineiter.next())
            lineiter.next() 
            metrics[ld]["gauge-iops"] = float(lineiter.next())
            lineiter.next()
            lineiter.next()
            lineiter.next()
            lineiter.next()
            lineiter.next()
            metrics[ld]["latency"] = float(lineiter.next())

        #controller B
        cmd_b.wait()
        for r in range(0,7):
            reader_b.next()
        for line in reader_b:
            lineiter = iter(line)
            ld = lineiter.next().replace("Virtual Disk ","")
            lineiter.next() # Ignore Total IOs

            metrics[ld]["percent-read_ratio"] += float(lineiter.next())
            metrics[ld]["percent-primary_read_cache_hit"] += float(lineiter.next())
            metrics[ld]["percent-primary_write_cache_hit"] += float(lineiter.next())
            lineiter.next() # Ignore SSD read cache hit
            metrics[ld]["gauge-throughput"] += float(lineiter.next())
            lineiter.next() 
            metrics[ld]["gauge-iops"] += float(lineiter.next())
            lineiter.next()
            lineiter.next()
            lineiter.next()
            lineiter.next()
            lineiter.next()
            metrics[ld]["latency"] += float(lineiter.next())

	write_metrics(metrics,host)

parser = argparse.ArgumentParser(description='Monitor Dell MD Array performance stats via collectd')
parser.add_argument('name', help='Name of array')
parser.add_argument('controller_a', help='hostname or IP of controller A')
parser.add_argument('controller_b', help='hostname or IP of controller B')
args = parser.parse_args()

while True:
        get_metrics(args.name,args.controller_a,args.controller_b)
